### Show that A = 4\*eye(4) - ones(4,4) is not invertible: Multiply A\*ones(4,1)

In [21]:
'''We import the packages to use in the script'''
import numpy as np

In [22]:
'''We create our matrix 4 by 4'''
A = np.eye(4) - np.ones((4,4))
print(A)


[[ 0. -1. -1. -1.]
 [-1.  0. -1. -1.]
 [-1. -1.  0. -1.]
 [-1. -1. -1.  0.]]


In [23]:
x = np.ones((4,1))
b = A @ x 
print(b)

[[-3.]
 [-3.]
 [-3.]
 [-3.]]


A is invertible because _x = A<sup>-1</sup>Ax = A<sup>-1</sup>b_ for that reason there is a matrix that multipy by A<sup>-1</sup> gives x in this case is ones(4,1) in this case is the followin matrix 

In [24]:
Inverse = np.array([[2/3,-1/3,-1/3,-1/3],[-1/3,2/3,-1/3,-1/3],[-1/3,-1/3,2/3,-1/3],[-1/3,-1/3,-1/3,2/3]])
print(Inverse)

[[ 0.66666667 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333  0.66666667]]


In [25]:
print(f"{Inverse} by {b} is equal to x\n")
print(f"and {A} by {x}  is equal to b\n")

[[ 0.66666667 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333  0.66666667]] by [[-3.]
 [-3.]
 [-3.]
 [-3.]] is equal to x

and [[ 0. -1. -1. -1.]
 [-1.  0. -1. -1.]
 [-1. -1.  0. -1.]
 [-1. -1. -1.  0.]] by [[1.]
 [1.]
 [1.]
 [1.]]  is equal to b

